title: explic.AI

description: >
  *explic.AI* is a research project aimed at enhancing the transparency and interpretability of artificial intelligence systems.

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
 - team/README.md
 - products.md
 - publication.md

minima:
  skin: classic
